# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 880)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Snoopy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 750, 1091, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gcode_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gcode_button.setFont(font)
        self.gcode_button.setObjectName("gcode_button")
        self.horizontalLayout.addWidget(self.gcode_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.show_bottom = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.show_bottom.setFont(font)
        self.show_bottom.setObjectName("show_bottom")
        self.horizontalLayout.addWidget(self.show_bottom)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.close_botton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.close_botton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.close_botton.setFont(font)
        self.close_botton.setObjectName("close_botton")
        self.horizontalLayout.addWidget(self.close_botton)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(310, 10, 871, 721))
        self.groupBox.setObjectName("groupBox")
        self.img_main = QtWidgets.QLabel(self.groupBox)
        self.img_main.setGeometry(QtCore.QRect(40, 40, 780, 585))
        self.img_main.setText("")
        self.img_main.setObjectName("img_main")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(210, 640, 91, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.img_roi = QtWidgets.QLabel(self.groupBox)
        self.img_roi.setGeometry(QtCore.QRect(360, 640, 60, 60))
        self.img_roi.setText("")
        self.img_roi.setObjectName("img_roi")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 10, 261, 411))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 440, 261, 291))
        self.groupBox_3.setObjectName("groupBox_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1205, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionds = QtWidgets.QAction(MainWindow)
        self.actionds.setObjectName("actionds")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.actionds)
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.close_botton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "監控平台"))
        self.gcode_button.setText(_translate("MainWindow", "Gcode指令傳輸"))
        self.show_bottom.setText(_translate("MainWindow", "開啟影像串流"))
        self.close_botton.setText(_translate("MainWindow", "關閉"))
        self.groupBox.setTitle(_translate("MainWindow", "Showing"))
        self.label.setText(_translate("MainWindow", "ROI窗口"))
        self.groupBox_2.setTitle(_translate("MainWindow", "列印參數回傳"))
        self.groupBox_3.setTitle(_translate("MainWindow", "列印狀態回傳"))
        self.menu.setTitle(_translate("MainWindow", "檔案"))
        self.menu_2.setTitle(_translate("MainWindow", "介面風格"))
        self.menu_3.setTitle(_translate("MainWindow", "關於"))
        self.actionds.setText(_translate("MainWindow", "開啟檔案"))
        self.actionds.setStatusTip(_translate("MainWindow", "監控即時列印狀況"))
        self.actionds.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.action.setText(_translate("MainWindow", "輸出狀態表"))
        self.action.setStatusTip(_translate("MainWindow", "以圖表方式分析影像以及列印數據"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.action_2.setText(_translate("MainWindow", "影像數據分析"))
        self.action_2.setShortcut(_translate("MainWindow", "Ctrl+3"))

