# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 880)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/Snoopy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 730, 1091, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gcode_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gcode_button.setFont(font)
        self.gcode_button.setStyleSheet("background-color: rgb(79, 79, 79);\n"
"color: rgb(255, 255, 255);")
        self.gcode_button.setObjectName("gcode_button")
        self.horizontalLayout.addWidget(self.gcode_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.show_bottom = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.show_bottom.setFont(font)
        self.show_bottom.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(79, 79, 79);")
        self.show_bottom.setObjectName("show_bottom")
        self.horizontalLayout.addWidget(self.show_bottom)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.close_botton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.close_botton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.close_botton.setFont(font)
        self.close_botton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(79, 79, 79);")
        self.close_botton.setObjectName("close_botton")
        self.horizontalLayout.addWidget(self.close_botton)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(310, 10, 871, 711))
        self.groupBox.setObjectName("groupBox")
        self.img_main = QtWidgets.QLabel(self.groupBox)
        self.img_main.setGeometry(QtCore.QRect(40, 20, 780, 585))
        self.img_main.setText("")
        self.img_main.setObjectName("img_main")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(660, 630, 91, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.img_roi = QtWidgets.QLabel(self.groupBox)
        self.img_roi.setGeometry(QtCore.QRect(770, 630, 60, 60))
        self.img_roi.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.img_roi.setText("")
        self.img_roi.setObjectName("img_roi")
        self.tableView = QtWidgets.QTableView(self.groupBox)
        self.tableView.setGeometry(QtCore.QRect(90, 630, 501, 61))
        self.tableView.setStyleSheet("background-color: rgb(105, 105, 105);")
        self.tableView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableView.setMidLineWidth(0)
        self.tableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView.setShowGrid(True)
        self.tableView.setSortingEnabled(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView.horizontalHeader().setDefaultSectionSize(98)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 10, 261, 381))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 241, 311))
        self.label_3.setObjectName("label_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 410, 261, 311))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_class = QtWidgets.QLabel(self.groupBox_3)
        self.label_class.setGeometry(QtCore.QRect(20, 50, 211, 81))
        self.label_class.setObjectName("label_class")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1020, 820, 171, 20))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1205, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionds = QtWidgets.QAction(MainWindow)
        self.actionds.setObjectName("actionds")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.actionds)
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.close_botton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "監控平台"))
        self.gcode_button.setText(_translate("MainWindow", "Gcode指令傳輸"))
        self.show_bottom.setText(_translate("MainWindow", "開啟影像串流"))
        self.close_botton.setText(_translate("MainWindow", "關閉"))
        self.groupBox.setTitle(_translate("MainWindow", "列印畫面"))
        self.label.setText(_translate("MainWindow", "ROI窗口"))
        self.groupBox_2.setTitle(_translate("MainWindow", "列印參數"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#000000;\">製程 : </span><span style=\" font-size:14pt; font-weight:600; color:#000000;\">材料擠製ME</span></p><p><span style=\" font-size:14pt; color:#000000;\">機台 : XYZ型Prusa i3</span></p><p><span style=\" font-size:14pt; color:#000000;\">最大列印範圍 : 150x150x150mm</span></p><p><span style=\" font-size:14pt; color:#000000;\">線材 : 消光PLA</span></p><p><span style=\" font-size:14pt; color:#000000;\">線材直徑 : 1.75mm</span></p><p><span style=\" font-size:14pt; color:#000000;\">層高 : 0.2mm</span></p><p><span style=\" font-size:14pt; color:#000000;\">噴頭溫度 : 225</span></p><p><span style=\" font-size:14pt; color:#000000;\">平台溫度 : 60</span></p><p><br/></p><p><br/></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "列印狀態"))
        self.label_class.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#000000;\">未連線</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic; color:#0000ff;\">made by AM LAB in 2019</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "檔案"))
        self.menu_2.setTitle(_translate("MainWindow", "介面風格"))
        self.menu_3.setTitle(_translate("MainWindow", "關於"))
        self.actionds.setText(_translate("MainWindow", "開啟檔案"))
        self.actionds.setStatusTip(_translate("MainWindow", "監控即時列印狀況"))
        self.actionds.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.action.setText(_translate("MainWindow", "輸出狀態表"))
        self.action.setStatusTip(_translate("MainWindow", "以圖表方式分析影像以及列印數據"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.action_2.setText(_translate("MainWindow", "影像數據分析"))
        self.action_2.setShortcut(_translate("MainWindow", "Ctrl+3"))


